### ISSUE TITLE
Set up Database for the Project - Chad

### ISSUE THREAD

**Issue by Raymond-Schooley** [CSS450Group2/ProjectMain#34]
Follow Lab4tack2 directions to clone our empty heroku app.  You should even use the same starter code.  The login credentials are: login email: css450team2@gmail.com, password: charlesbryan450! Follow lab steps starting at 28, "Writing a web service that connects to a database".  Our goal to modularize our database connection like we are instructed towards the end of the app right away so skip the intermediate steps where everything is in index.js

*After setting up tables insert one entry into Members, the TestUser.  Give TestUser token values and let other team members know the MemberID for the TestUser.

**Comment by ChadChapman** [comment]
db is live, has a test user with this info: 
rabbitchat-backend::DATABASE=> SELECT MemberID AS id, FirstName AS first, LastName AS last, Username FROM Members;
 id | first | last | username
----+-------+------+----------
  1 | tt    | gg   | bb
(1 row)
